### ISSUE TITLE
Trying to determine the source of problem

### ISSUE THREAD

**Issue by alex-kovac** [carlenlund/helmet#5]
I have difficulty opening Helmet Neue source files, it seems.

- When opening HelmetNeue-Regular.otf, the error:
(*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0])
- When opening Helmet Neue glyphs file I cannot see any glyphs.

Anyone else having the same problem?

**Comment by carlenlund** [comment]
I don't have access to Glyphs, so I'm afraid I don't know what's causing the first error. Please refer to the [Glyphs Forum](https://forum.glyphsapp.com/) if the problem remains.

I exported HelmetNeue-Regular.glyphs using FontLab, and I'm thinking that's causing the second error. I've attached a .zip where the project has been exported using the setting "DesignSpace". See if you're able to open this in Glyphs. It would be nice to have source files that can be used both in FontLab and Glyphs.

Let me know if you'd like to make any specific changes and I'm sure we can work something out.

[helmet-neue-designspace.zip](https://github.com/carlenlund/helmet/files/3694079/helmet-neue-designspace.zip)

**Comment by alex-kovac** [comment]
Thank you for the file. Yes, UFO file opens nicely in Glyphs and FontLab. Perhaps then UFO format would be a good source file format? I must say that I do not have experience using UFO format and am not aware of its shortcomings (if any).
