### ISSUE TITLE
images/helmet-{1,2,4}.png showing Helmet rather than Helmet Neue?

### ISSUE THREAD

**Issue by hartwork** [carlenlund/helmet#6]
Hi!

Based on the files changes by 1bce5f6c20f495d945bfc660b123850d5c015de4 and the listing view at https://github.com/carlenlund/helmet/tree/master/images my impression is that files `images/helmet-{1,2,4}.png` feature Helmet, not Helmet Neue. Is that intended?

Thanks and best, Sebastian

**Comment by carlenlund** [comment]
Hi Sebastian! Good catch, the images still show the old version of Helmet. I didn't feel it was necessary to make images for the new version since most of the changes were quite small.
